<?php
/**
 * ContextInterface.php
 * Generated by PhpStorm - 02/2016
 * Project bentools-etl
 * @author Beno!t POLASZEK
 **/

namespace BenTools\ETL\Interfaces;

interface ContextInterface {

    /**
     * @return array
     */
    public function getExtractedData();

    /**
     * @param $data
     * @return $this - Provides fluent interface
     */
    public function setExtractedData($data);

    /**
     * @return mixed
     */
    public function getTransformedData();

    /**
     * @param $data
     * @return $this - Provides fluent interface
     */
    public function setTransformedData($data);

    /**
     * @return int|string
     */
    public function getIdentifier();

    /**
     * @param int|string the identifier value of current data
     **/
    public function setIdentifier($id);

    /**
     * Indicates if the ETL should skip this row.
     * @return boolean
     */
    public function shouldSkip($value = null);

    /**
     * Indicates if the ETL should stop and go flushing.
     * @return boolean
     */
    public function shouldBreak($value = null);

    /**
     * Indicates if the ETL should stop and not flush anything.
     * @return boolean
     */
    public function shouldHalt($value = null);

    /**
     * Indicates if the ETL should flush.
     * @return boolean
     */
    public function shouldFlush($value = null);
}