<?php
/**
 * TransformerInterface.php
 * Generated by PhpStorm - 02/2016
 * Project bentools-etl
 * @author Beno!t POLASZEK
 **/

namespace BenTools\ETL\Interfaces;

interface TransformerInterface {

    /**
     * @param $data
     * @param ContextInterface $context
     * @return mixed
     */
    public function transform($data, ContextInterface $context);
}