<?php
/**
 * CallbackTransformer.php
 * Generated by PhpStorm - 02/2016
 * Project bentools-etl
 * @author Beno!t POLASZEK
 **/

namespace BenTools\ETL\Transformer;

use BenTools\ETL\Interfaces\ContextInterface;
use BenTools\ETL\Interfaces\TransformerInterface;

class CallbackTransformer implements TransformerInterface {

    private $callback;

    public function __construct(callable $callback) {
        $this->callback = $callback;
    }

    public function transform($data, ContextInterface $context) {
        return call_user_func($this->callback, $data, $context);
    }

}